#!/bin/bash

REPO=$1

# Determine Repo Type
#
[ -d "$REPO/.git" ] && UPDATE_CMD=git_update
[ -d "$REPO/.svn" ] && UPDATE_CMD='svn update'
[ -d "$REPO/.hg"  ] && UPDATE_CMD='hg pull'

( cd "$REPO" && $UPDATE_CMD )


git_update()
{
    git remote | while read REMOTE
    do
        git fetch "$REMOTE"
    done
}
