#!/bin/bash

MANIFEST="$1"
MANIFEST_TMP=`mktemp`
MANIFEST_DIR=`dirname "$MANIFEST"`

# Make sure that everything is absolute. Anything that is relative is prepended
# with the directory of the MANIFEST file.
egrep -v '^#' "$MANIFEST" \
    | egrep '^/' >> "$MANIFEST_TMP"
egrep -v '^#' "$MANIFEST" \
    | egrep -v '^/' \
    | sed 's:^:'$MANIFEST_DIR'\/:' >> "$MANIFEST_TMP"

cat "$MANIFEST_TMP" | while read REPO
do
    repo-update "$REPO"
done

rm "$MANIFEST_TMP"
