#!/bin/bash

# fesc = font escape
function fesc
{
    echo -ne "\033]710;$*\007"
}

function set_font
{
    case $1 in
        terminus8px)
            fesc "xft:Terminus:pixelsize=8:antialias=false:autohinting=true"
            ;;
        terminus8pt)
            fesc "xft:Terminus-8:antialias=false:autohinting=true"
            ;;
        fixed11)
            fesc "xft:Fixed:pixelsize=11:antialias=false:autohinting=true"
            ;;
        deja8pt)
            fesc "xft:Deja Vu Sans Mono-8:antialias=false:autohinting=true"
            ;;
        deja8ptaa)
            fesc "xft:Deja Vu Sans Mono-8:antialias=true:autohinting=true"
            ;;
        deja9px)
            fesc "xft:Deja Vu Sans Mono:pixelsize=9:antialias=false:autohinting=true"
            ;;
        deja9pxaa)
            fesc "xft:Deja Vu Sans Mono:pixelsize=9:antialias=true:autohinting=true"
            ;;
        deja10px)
            fesc "xft:Deja Vu Sans Mono:pixelsize=10:antialias=false:autohinting=true"
            ;;
        deja10pxaa)
            fesc "xft:Deja Vu Sans Mono:pixelsize=10:antialias=true:autohinting=true"
            ;;
        deja10pt)
            fesc "xft:Deja Vu Sans Mono-10:antialias=false:autohinting=true"
            ;;
        *)
            echo "'$1' is not a font setup."
            exit 1
            ;;
    esac
}


set_font $1
