#!/bin/sh

# xmutt - X11 Mutt
#   Command to make it easy to start up a terminal with mutt in it.
#   * Supports rxvt/urxvt/xterm out of the box (CLI options are compatible with
#     all three).
#   * Using the -name option allows themeing specific to xmutt instances in the
#     ~/.Xdefaults file.
#   * Defaults to using xterm as the terminal, but this can be changed with the
#     $XMUTT_TERM variable so long as the terminal supports the -title/-name/-e
#     options.

[ -z  $XMUTT_TERM ] && XMUTT_TERM=xterm
exec $XMUTT_TERM -title 'xmutt' -name 'xmutt' -e mutt $@
